version: '3.3'
services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:8000"
    depends_on:
      - db
    env_file:
      - ./.env

volumes:
  db_value:
