"""comment1

Revision ID: 6e73da5ce4b5
Revises: 3e8101940da2
Create Date: 2023-06-09 22:40:10.018468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e73da5ce4b5'
down_revision = '3e8101940da2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
