"""add audio table

Revision ID: 8c8b40d9274e
Revises: cd17245eb798
Create Date: 2023-06-10 01:49:01.462708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c8b40d9274e'
down_revision = 'cd17245eb798'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audiofile',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('filepath', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('hren')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hren',
    sa.Column('a', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('a', name='hren_pkey')
    )
    op.drop_table('audiofile')
    # ### end Alembic commands ###
