"""add FK to audiofile

Revision ID: d3d9c3919447
Revises: 8c8b40d9274e
Create Date: 2023-06-12 15:27:50.770050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3d9c3919447'
down_revision = '8c8b40d9274e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audiofile', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'audiofile', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'audiofile', type_='foreignkey')
    op.drop_column('audiofile', 'user_id')
    # ### end Alembic commands ###
